language: node_js
node_js: "lts/*"

before_script:
  - npm install -g gulp-cli

script:
  - cd ui && yarn install && gulp preview:build && gulp bundle

cache:
  yarn: true
  directories:
    - $HOME/.cache
